name: first-action
run-name: instance
on: [push]

jobs:
  build:
    strategy:
      matrix:
        versions: ["3.8","3.9", "3.10","3.11"]
      
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello World"
    - name: Checkout
      uses: actions/checkout@v3.5.3
    - uses: actions/setup-python@v3.1.4
      with:
        python-version: ${{ matrix.versions }}
    - run: python -m pip install Flask
    - run: python test.py


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploying"


  
